const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Behaviors.Tween,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.video,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Exps.TouchCount,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Touch.Exps.XAt,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.YAt,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.IsBetweenAngles,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.video.Acts.SetSource2,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.video.Acts.SetPlaybackTime,
		C3.Plugins.video.Acts.SetVisible,
		C3.Plugins.video.Acts.Pause,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Audio.Cnds.IsTagPlaying
	];
};
self.C3_JsPropNameTable = [
	{"8Direction": 0},
	{Platform: 0},
	{BoundToLayout: 0},
	{ScrollTo: 0},
	{C: 0},
	{Solid: 0},
	{T_S_npc1: 0},
	{T_S_npc2: 0},
	{T_S_npc3: 0},
	{T_S_npc4: 0},
	{Sprite2: 0},
	{DragDrop: 0},
	{T_S_v13: 0},
	{T_S_v14: 0},
	{T_S_v12: 0},
	{T_S_v11: 0},
	{T_optionbg: 0},
	{T_seat_s1: 0},
	{T_seat_s2: 0},
	{T_seat_s3: 0},
	{T_seat_s4: 0},
	{T_seat_s5: 0},
	{T_seat_s6: 0},
	{T_Seat_t1: 0},
	{T_optionbg2: 0},
	{T_S_v24: 0},
	{T_S_v22: 0},
	{T_S_v23: 0},
	{T_S_v21: 0},
	{T_Seat_t2: 0},
	{T_seat_w1: 0},
	{T_seat_w2: 0},
	{T_seat_w3: 0},
	{T_seat_w4: 0},
	{T_seat_w5: 0},
	{T_seat_w6: 0},
	{T_S_v25: 0},
	{T_optionbg3: 0},
	{T_seat_b1: 0},
	{T_seat_b2: 0},
	{T_seat_b3: 0},
	{T_seat_b4: 0},
	{T_S_v31: 0},
	{T_S_v34: 0},
	{T_S_v32: 0},
	{T_S_v33: 0},
	{T_Seat_t12: 0},
	{T_seat_b5: 0},
	{T_optionbg4: 0},
	{T_S_v44: 0},
	{T_S_v41: 0},
	{T_S_v42: 0},
	{T_S_v43: 0},
	{T_Seat_t13: 0},
	{T_seat_p1: 0},
	{T_seat_p2: 0},
	{T_seat_p3: 0},
	{T_seat_p4: 0},
	{T_seat_bg: 0},
	{Anchor: 0},
	{B_Question: 0},
	{B_back: 0},
	{B_home: 0},
	{H_string: 0},
	{H_bg: 0},
	{H_cube: 0},
	{Tank: 0},
	{H_bg2: 0},
	{H_bg3: 0},
	{H_bg4: 0},
	{H_woodwind: 0},
	{H_Brass: 0},
	{H_percussion: 0},
	{a: 0},
	{d: 0},
	{TArea: 0},
	{TPin: 0},
	{H_Seat: 0},
	{Sprite5: 0},
	{Sprite3: 0},
	{bg_land: 0},
	{bg_c1: 0},
	{bg_c4: 0},
	{bg_c2: 0},
	{bg_c3: 0},
	{bg_t1: 0},
	{Sprite: 0},
	{bg_t4: 0},
	{bg_t2: 0},
	{bg_t3: 0},
	{S_learn: 0},
	{musician1: 0},
	{bg_L1: 0},
	{Tween: 0},
	{know1: 0},
	{know2: 0},
	{treasure1: 0},
	{treasure2: 0},
	{tree1: 0},
	{tree2: 0},
	{tree3: 0},
	{bg_h1: 0},
	{bg_h2: 0},
	{bg_hear: 0},
	{h1: 0},
	{h2: 0},
	{h3: 0},
	{h_speak: 0},
	{next: 0},
	{cube1: 0},
	{cube2: 0},
	{cube3: 0},
	{whiteBoard: 0},
	{h_q: 0},
	{B_learn: 0},
	{musician3: 0},
	{know3: 0},
	{know4: 0},
	{treasure3: 0},
	{treasure4: 0},
	{bg_L3: 0},
	{bg_link: 0},
	{Sprite4: 0},
	{L_b44: 0},
	{L_b11: 0},
	{L_b33: 0},
	{L_b22: 0},
	{L_b1: 0},
	{L_b2: 0},
	{L_b3: 0},
	{L_b4: 0},
	{line1: 0},
	{line3: 0},
	{line4: 0},
	{line2: 0},
	{dot1: 0},
	{L_s2: 0},
	{L_s1: 0},
	{L_s3: 0},
	{L_s4: 0},
	{L_s22: 0},
	{L_s44: 0},
	{L_s33: 0},
	{L_s11: 0},
	{bg_L2: 0},
	{treasure5: 0},
	{treasure6: 0},
	{know5: 0},
	{know6: 0},
	{W_learn: 0},
	{musician2: 0},
	{treasure7: 0},
	{treasure8: 0},
	{know7: 0},
	{bg_L4: 0},
	{P_learn: 0},
	{musician4: 0},
	{know8: 0},
	{Keyboard: 0},
	{Text: 0},
	{Touch: 0},
	{Mouse: 0},
	{Sprite6: 0},
	{Audio: 0},
	{Video: 0},
	{Sprite9: 0},
	{hear_sound: 0},
	{close: 0},
	{T_S_V1: 0},
	{H_town: 0},
	{T_S_V2: 0},
	{T_S_V3: 0},
	{T_S_V4: 0},
	{tree: 0},
	{hear_123: 0},
	{link_brass: 0},
	{link_string: 0},
	{showThumbstick: 0},
	{dist: 0},
	{T_npc: 0},
	{T_Seat: 0},
	{hear: 0},
	{toHear: 0},
	{Link: 0},
	{toLink: 0}
];

self.InstanceType = {
	C: class extends self.ISpriteInstance {},
	T_S_npc1: class extends self.ISpriteInstance {},
	T_S_npc2: class extends self.ISpriteInstance {},
	T_S_npc3: class extends self.ISpriteInstance {},
	T_S_npc4: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	T_S_v13: class extends self.ISpriteInstance {},
	T_S_v14: class extends self.ISpriteInstance {},
	T_S_v12: class extends self.ISpriteInstance {},
	T_S_v11: class extends self.ISpriteInstance {},
	T_optionbg: class extends self.ISpriteInstance {},
	T_seat_s1: class extends self.ISpriteInstance {},
	T_seat_s2: class extends self.ISpriteInstance {},
	T_seat_s3: class extends self.ISpriteInstance {},
	T_seat_s4: class extends self.ISpriteInstance {},
	T_seat_s5: class extends self.ISpriteInstance {},
	T_seat_s6: class extends self.ISpriteInstance {},
	T_Seat_t1: class extends self.ITextInstance {},
	T_optionbg2: class extends self.ISpriteInstance {},
	T_S_v24: class extends self.ISpriteInstance {},
	T_S_v22: class extends self.ISpriteInstance {},
	T_S_v23: class extends self.ISpriteInstance {},
	T_S_v21: class extends self.ISpriteInstance {},
	T_Seat_t2: class extends self.ITextInstance {},
	T_seat_w1: class extends self.ISpriteInstance {},
	T_seat_w2: class extends self.ISpriteInstance {},
	T_seat_w3: class extends self.ISpriteInstance {},
	T_seat_w4: class extends self.ISpriteInstance {},
	T_seat_w5: class extends self.ISpriteInstance {},
	T_seat_w6: class extends self.ISpriteInstance {},
	T_S_v25: class extends self.ISpriteInstance {},
	T_optionbg3: class extends self.ISpriteInstance {},
	T_seat_b1: class extends self.ISpriteInstance {},
	T_seat_b2: class extends self.ISpriteInstance {},
	T_seat_b3: class extends self.ISpriteInstance {},
	T_seat_b4: class extends self.ISpriteInstance {},
	T_S_v31: class extends self.ISpriteInstance {},
	T_S_v34: class extends self.ISpriteInstance {},
	T_S_v32: class extends self.ISpriteInstance {},
	T_S_v33: class extends self.ISpriteInstance {},
	T_Seat_t12: class extends self.ITextInstance {},
	T_seat_b5: class extends self.ISpriteInstance {},
	T_optionbg4: class extends self.ISpriteInstance {},
	T_S_v44: class extends self.ISpriteInstance {},
	T_S_v41: class extends self.ISpriteInstance {},
	T_S_v42: class extends self.ISpriteInstance {},
	T_S_v43: class extends self.ISpriteInstance {},
	T_Seat_t13: class extends self.ITextInstance {},
	T_seat_p1: class extends self.ISpriteInstance {},
	T_seat_p2: class extends self.ISpriteInstance {},
	T_seat_p3: class extends self.ISpriteInstance {},
	T_seat_p4: class extends self.ISpriteInstance {},
	T_seat_bg: class extends self.ISpriteInstance {},
	B_Question: class extends self.ISpriteInstance {},
	B_back: class extends self.ISpriteInstance {},
	B_home: class extends self.ISpriteInstance {},
	H_string: class extends self.ISpriteInstance {},
	H_bg: class extends self.ISpriteInstance {},
	H_cube: class extends self.ISpriteInstance {},
	Tank: class extends self.ISpriteInstance {},
	H_bg2: class extends self.ISpriteInstance {},
	H_bg3: class extends self.ISpriteInstance {},
	H_bg4: class extends self.ISpriteInstance {},
	H_woodwind: class extends self.ISpriteInstance {},
	H_Brass: class extends self.ISpriteInstance {},
	H_percussion: class extends self.ISpriteInstance {},
	TArea: class extends self.ISpriteInstance {},
	TPin: class extends self.ISpriteInstance {},
	H_Seat: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	bg_land: class extends self.ISpriteInstance {},
	bg_c1: class extends self.ISpriteInstance {},
	bg_c4: class extends self.ISpriteInstance {},
	bg_c2: class extends self.ISpriteInstance {},
	bg_c3: class extends self.ISpriteInstance {},
	bg_t1: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	bg_t4: class extends self.ISpriteInstance {},
	bg_t2: class extends self.ISpriteInstance {},
	bg_t3: class extends self.ISpriteInstance {},
	S_learn: class extends self.ISpriteInstance {},
	musician1: class extends self.ISpriteInstance {},
	bg_L1: class extends self.ISpriteInstance {},
	know1: class extends self.ISpriteInstance {},
	know2: class extends self.ISpriteInstance {},
	treasure1: class extends self.ISpriteInstance {},
	treasure2: class extends self.ISpriteInstance {},
	tree1: class extends self.ISpriteInstance {},
	tree2: class extends self.ISpriteInstance {},
	tree3: class extends self.ISpriteInstance {},
	bg_h1: class extends self.ISpriteInstance {},
	bg_h2: class extends self.ISpriteInstance {},
	bg_hear: class extends self.ISpriteInstance {},
	h1: class extends self.ISpriteInstance {},
	h2: class extends self.ISpriteInstance {},
	h3: class extends self.ISpriteInstance {},
	h_speak: class extends self.ISpriteInstance {},
	next: class extends self.ISpriteInstance {},
	cube1: class extends self.ISpriteInstance {},
	cube2: class extends self.ISpriteInstance {},
	cube3: class extends self.ISpriteInstance {},
	whiteBoard: class extends self.ISpriteInstance {},
	h_q: class extends self.ISpriteInstance {},
	B_learn: class extends self.ISpriteInstance {},
	musician3: class extends self.ISpriteInstance {},
	know3: class extends self.ISpriteInstance {},
	know4: class extends self.ISpriteInstance {},
	treasure3: class extends self.ISpriteInstance {},
	treasure4: class extends self.ISpriteInstance {},
	bg_L3: class extends self.ISpriteInstance {},
	bg_link: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	L_b44: class extends self.ISpriteInstance {},
	L_b11: class extends self.ISpriteInstance {},
	L_b33: class extends self.ISpriteInstance {},
	L_b22: class extends self.ISpriteInstance {},
	L_b1: class extends self.ISpriteInstance {},
	L_b2: class extends self.ISpriteInstance {},
	L_b3: class extends self.ISpriteInstance {},
	L_b4: class extends self.ISpriteInstance {},
	line1: class extends self.ISpriteInstance {},
	line3: class extends self.ISpriteInstance {},
	line4: class extends self.ISpriteInstance {},
	line2: class extends self.ISpriteInstance {},
	dot1: class extends self.ISpriteInstance {},
	L_s2: class extends self.ISpriteInstance {},
	L_s1: class extends self.ISpriteInstance {},
	L_s3: class extends self.ISpriteInstance {},
	L_s4: class extends self.ISpriteInstance {},
	L_s22: class extends self.ISpriteInstance {},
	L_s44: class extends self.ISpriteInstance {},
	L_s33: class extends self.ISpriteInstance {},
	L_s11: class extends self.ISpriteInstance {},
	bg_L2: class extends self.ISpriteInstance {},
	treasure5: class extends self.ISpriteInstance {},
	treasure6: class extends self.ISpriteInstance {},
	know5: class extends self.ISpriteInstance {},
	know6: class extends self.ISpriteInstance {},
	W_learn: class extends self.ISpriteInstance {},
	musician2: class extends self.ISpriteInstance {},
	treasure7: class extends self.ISpriteInstance {},
	treasure8: class extends self.ISpriteInstance {},
	know7: class extends self.ISpriteInstance {},
	bg_L4: class extends self.ISpriteInstance {},
	P_learn: class extends self.ISpriteInstance {},
	musician4: class extends self.ISpriteInstance {},
	know8: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Video: class extends self.IWorldInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	hear_sound: class extends self.ISpriteInstance {},
	close: class extends self.ISpriteInstance {},
	T_S_V1: class extends self.ISpriteInstance {},
	H_town: class extends self.ISpriteInstance {},
	T_S_V2: class extends self.ISpriteInstance {},
	T_S_V3: class extends self.ISpriteInstance {},
	T_S_V4: class extends self.ISpriteInstance {},
	tree: class extends self.ISpriteInstance {},
	hear_123: class extends self.ISpriteInstance {},
	link_brass: class extends self.ISpriteInstance {},
	link_string: class extends self.ISpriteInstance {}
}